### ISSUE TITLE
Would Viper be a good addition?

### ISSUE THREAD

**Issue by james1293** [awesomo4000/awesome-provable#3]
Hello all,
Would [Viper](https://www.pm.inf.ethz.ch/research/viper.html) (also on [Github](https://github.com/viperproject)) be a good addition to this list?

**Comment by awesomo4000** [comment]
That looks pretty neat.

**Comment by james1293** [comment]
Ya! Do you think it would go in "projects" or "proof assistants"? Or a new category?

**Comment by awesomo4000** [comment]
No opinion on that. Feel free to submit a pull request.
